"""empty message

Revision ID: 2e02f7947fe6
Revises: 
Create Date: 2024-05-18 18:30:52.449971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e02f7947fe6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=75), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('idCliente'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('metodo_pago',
    sa.Column('idMetodo_pago', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idMetodo_pago')
    )
    op.create_table('tipo_servicio',
    sa.Column('idTipo_servicio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idTipo_servicio')
    )
    op.create_table('pedido',
    sa.Column('idPedido', sa.Integer(), nullable=False),
    sa.Column('pedido_ropa', sa.String(length=50), nullable=False),
    sa.Column('pedido_cantidad', sa.String(length=10), nullable=False),
    sa.Column('observacion', sa.String(length=200), nullable=True),
    sa.Column('fecha_servicio', sa.Date(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('idMetodo_pago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.idCliente'], ),
    sa.ForeignKeyConstraint(['idMetodo_pago'], ['metodo_pago.idMetodo_pago'], ),
    sa.PrimaryKeyConstraint('idPedido')
    )
    op.create_table('pedido_servicio',
    sa.Column('idPedido_servicio', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('idPedido', sa.Integer(), nullable=False),
    sa.Column('idTipo_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPedido'], ['pedido.idPedido'], ),
    sa.ForeignKeyConstraint(['idTipo_servicio'], ['tipo_servicio.idTipo_servicio'], ),
    sa.PrimaryKeyConstraint('idPedido_servicio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_servicio')
    op.drop_table('pedido')
    op.drop_table('tipo_servicio')
    op.drop_table('metodo_pago')
    op.drop_table('cliente')
    # ### end Alembic commands ###
