"""Agregando campo de contraseña al modelo Cliente

Revision ID: a9795ac08d0d
Revises: 2e02f7947fe6
Create Date: 2024-05-21 22:32:11.505449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9795ac08d0d'
down_revision = '2e02f7947fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###
