"""empty message

Revision ID: d98323ce45d4
Revises: 101a3fa08c9c
Create Date: 2024-05-23 01:30:24.640511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98323ce45d4'
down_revision = '101a3fa08c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('contraseña',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('contraseña',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
